
name: Deploy

on:
  push:
    tags:
      - "v*"

jobs:
  release-qgis-repo:
    name: Deploy to QGIS plugin repository
    runs-on: ubuntu-24.04

    steps:
      - uses: actions/checkout@v

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install qgis-plugin-ci
        run: pip install qgis-plugin-ci>=2.8.6

      - name: Deploy to QGIS plugin repository
        env:
          OSGEO_USERNAME: ${{ secrets.OSGEO_USERNAME }}
          OSGEO_PASSWORD: ${{ secrets.OSGEO_PASSWORD }}
        run: qgis-plugin-ci release --osgeo-username "$OSGEO_USERNAME" --osgeo-password "$OSGEO_PASSWORD" "${GITHUB_REF##*/v}"
